spring:
  application:
    name: kservice
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/mithra_db?ssl=false&sslmode=disable

  flyway:
    enabled: true
    locations: classpath:/db/migration/dev
    table: mithra_schema_history