CREATE TABLE mithra_user (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   user_id UUID NOT NULL DEFAULT uuid_generate_v4(),
   email VARCHAR(255) UNIQUE NOT NULL,
   password VARCHAR(255) NOT NULL,
   first_name VARCHAR(255),
   last_name VARCHAR(255),
   role VARCHAR(50) DEFAULT 'MEMBER',
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   is_active BOOLEAN DEFAULT TRUE,
   profile_picture VARCHAR(255),
   bio TEXT,
   public_profile BOOLEAN DEFAULT TRUE
);

-- Index for faster lookups by email
CREATE INDEX idx_mithra_user_email ON mithra_user(email);

CREATE TABLE mithra_session (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  user_role VARCHAR(10) DEFAULT NULL,
  session_id VARCHAR(255) UNIQUE NOT NULL,
  ip_address VARCHAR(45),
  user_agent VARCHAR(255),
  message VARCHAR(255) DEFAULT NULL,
  status VARCHAR(40) NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ended_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES mithra_user(id) ON DELETE CASCADE
);

-- Index for session_token for quick lookups
CREATE INDEX idx_session_token ON mithra_session(session_id);